name: loanstatus
channels:
  - conda-forge
  - nodefaults
  - defaults
dependencies:
  - python = 3.12
  - pandas = 2.3
  - numpy = 1.26
  - seaborn = 0.13
  - matplotlib = 3.10
  - plotly = 6.5
  - scikit-learn = 1.7